spring:
  application:
    name: capstone

  datasource:
    url: jdbc:mysql://localhost:3306/capstone_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1500MB
      enabled: true

  thymeleaf:
    cache: false

server:
  port: 8080
  tomcat:
    max-part-count: 5000

minio:
  url: http://localhost:9000
  bucket:
    name: capstone
  access:
    key: minioadmin
  secret:
    key: minioadmin
